[project]
site_name = "Universal Robots Vision Interface"
site_description = "Example Polyscope X integration for the generic wenglor vision interface"
site_url = "https://wenglor.github.io/robot-vision-ur-polyscopex/"
repo_url = "https://github.com/wenglor/robot-vision-ur-polyscopex"
repo_name = "robot-vision-ur-polyscopex"
edit_uri = "edit/main/docs/"
copyright = "© 2026 wenglor sensoric group"

extra_css = [
  "css/wenglor.css",
  "css/image_format.css",
]

[project.theme]
name = "material"
variant = "modern"
logo = "images/wenglor_logo.svg"
favicon = "images/favicon.ico"
language = "en"
features = [
  "navigation.instant",
  "navigation.instant.progress",
  "navigation.tracking",
  "navigation.indexes",
  "navigation.top",
  "navigation.footer",
  "navigation.path",
  "toc.follow",
  "content.code.copy",
  "content.tabs.link",
  "content.tooltips",
  "content.action.edit",
  "search.highlight",
  "search.suggest",
  "search.share",
]

[project.theme.font]
text = "Inter"
code = "JetBrains Mono"

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "custom"
accent = "custom"
[project.theme.palette.toggle]
icon = "material/brightness-7"
name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "custom"
accent = "custom"
[project.theme.palette.toggle]
icon = "material/brightness-4"
name = "Switch to light mode"

nav = [
  "index.md",
  "1_0_0_installation.md",
  "2_0_0_user_configuration.md",
  "3_0_0_robot_program.md",
  "4_0_0_troubleshooting.md",
  "5_0_0_support_and_feedback.md",
]

[project.markdown_extensions]
admonition = {}
"pymdownx.details" = {}

attr_list = {}
md_in_html = {}

tables = {}
def_list = {}
abbr = {}

"pymdownx.highlight" = { anchor_linenums = true, line_spans = "__span", pygments_lang_class = true }
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = {}
"pymdownx.superfences" = { custom_fences = [{ name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_div_format" }] }

"pymdownx.blocks.html" = {}
"pymdownx.tabbed" = { alternate_style = true }
"pymdownx.keys" = {}
"pymdownx.tasklist" = { custom_checkbox = true }
"pymdownx.tilde" = {}
"pymdownx.caret" = {}
"pymdownx.mark" = {}
"pymdownx.smartsymbols" = {}
"pymdownx.betterem" = {}

toc = { permalink = true, permalink_title = "Link to this section" }

[[project.extra_javascript]]
path = "javascripts/mermaid.mjs"
type = "module"

[project.validation]
invalid_links = true
invalid_link_anchors = true

[project.extra]
generator = false
